# Assignment 3 Report

# Task 1

## task 1a)

<img src="task1a_1.png"><br>
<img src="task1a_2.png"><br>
<img src="task1a_3.png"><br>
<img src="task1a_4.png"><br>
<img src="task1a_5.png"><br>

In [1]:
import torch
import scipy 
import numpy as np   

x = np.array([[2,1,2,3,1],
              [3,9,1,1,4],
              [4,5,0,7,0]])
y = np.array([[-1,0,1],
              [-2,0,2],
              [-1,0,1]])
print(scipy.ndimage.convolve(x,y,mode='constant'))

[[-11   2   4  -1   7]
 [-24   8  12  -5  12]
 [-19  10   4  -3  15]]


## task 1b)

That is max pooling. Max pooling reduces the complexity of the image by keeping the maximum value of pixels close to each other. This makes the network more invariant to small translations nad distoritions in the input. 

## task 1c)

To keep the dimensions:
$Padding = \frac{Kernel \, size - 1}{2}$

In this case kernel size is 7:
$Padding = \frac{7 - 1}{2} = 3$

## task 1d)

If the spatial dimensions of the features maps to 508x508 and no padding is used and the stride is 1, then the reduction in height and width will then be kernel size - 1. Since the reduction is 512-508=4, the kernel must be 5x5.
Output = 508, input = 512, padding = 0, stride = 1
 
$output = \frac{input - kernel size + 2 * padding}{stride} + 1$

$508 = 512 - K + 1 -> K = 5$

## task 1e)
Input = 508, kernel size = 2, padding = 0, stride = 2

$output = \frac{input - kernel size + 2 * padding}{stride} + 1$

$output = \frac{508 - 2}{2} + 1 = 254$

## task 1f)

Input = 254, kernel size = 3, padding = 0, stride = 1

$output = \frac{input - kernel size + 2 * padding}{stride} + 1$

$output = \frac{254 - 3}{1} + 1 = 252$

## task 1g)

params = weights + biases

Params in a convolutional layer:

$params = (k*k*M+1)*N$, where

k - kernel size<br>
M - number of filters in previous layer<br>
N - number of filters in a layer<br>


Params in a fully conected layer:

$params = N*(M+1)$

M - number of hidden units in previous layer<br>
N - number of hidden units in a layer<br>


Layer 1: $params = (5*5*3+1)*32 = 2432$<br>
Layer 2: $params = (5*5*32+1)*64 = 51 264$<br>
Layer 3: $params = (5*5*64+1)*128 = 204 928$<br>
Flatten after layer 3 gives number of units = 128 * 4 * 4 = 2048<br>
128 is number of filters in layer 3, 4 * 4 is given from the start 32x32 pixels that has been max pooled with 2x2 kernel and padding 2, three times.<br>
Layer 4: $params = 64(2048 + 1) = 131 136$<br>
Layer 5: $params = 10(128 + 1) = 650$<br>

$Total params = 2432 + 51 264 + 204 928 + 131 136 + 650 = 390 410$

# Task 2

### Task 2a)
<img src="plots/task2.png">


### Task 2b)
<img src="task2_accuracy.png">
Training accuracy: 0.878<br>
Validation accuracy: 0.730<br>
Test accuracy: 0.7342

# Task 3

### Task 3a)
| Layer | Layer Type        | Number of Hidden Units / Number of Filters | Activation Function |
|-------|-------------------|-------------------------------------------|----------------------|
| 1     | Conv2D            | 32                                        | ReLU                 |
| 1     | MaxPool2D         | –                                         | –                    |
| 2     | Conv2D            | 128                                       | ReLU                 |
| 2     | MaxPool2D         | –                                         | –                    |
| 3     | Conv2D            | 256                                       | ReLU                 |
| 3     | MaxPool2D         | –                                         | –                    |
| Flatten | –               | –                                         | –                    |
| 4     | Fully-Connected   | 128                                       | ReLU                 |
| 5     | Fully-Connected   | 10                                        | Softmax              |

For all convolutional layers:<br>
Stride=1<br>
Padding=2<br>

Kernel for layer 1= 3x3<br>
Kernel for layer 2= 4x4<br>
Kernel for layer 3= 5x5<br>

Optimizer: sgd<br>
Regularization: None<br>
Learning rate: 0.05<br>
Batch size: 64<br>
Weight init: None<br>
Data augmentation: Used transforms.Lambda(random_rotate_images) and transforms.Lambda(random_color_jitter)<br>
Added batch normalization after every convolutional layer<br>
Early stopping: 4 epochs
### Task 3b)
<img src="plots/task3.png">

<img src="task3_accuracy.png">

### Task 3c)

### Task 3d)

### Task 3e)

### Task 3f)

# Task 4

Optimizer: adam<br>
Batch size: 32 <br>
Learning rate: 5*10^-4<br>
Data augmentation: Resize til (112,112) <br>

<img src="plots/task4.png">

<img src="task4_accuracy.png">